# Generated by Django 5.0.6 on 2024-09-01 05:44

import django.core.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Championat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age18', models.IntegerField(db_index=True, null=True, verbose_name='возраст до 18')),
                ('age35', models.IntegerField(db_index=True, null=True, verbose_name='возраст 18-35')),
                ('age49', models.IntegerField(db_index=True, verbose_name='возраст 36-49')),
                ('ageover50', models.IntegerField(db_index=True, null=True, verbose_name='возраст 50+')),
                ('balls', models.IntegerField(db_index=True, null=True, verbose_name='баллы')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teams', verbose_name='команда')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_select', models.IntegerField(null=True, verbose_name='день пробежки')),
                ('photo', models.FileField(blank=True, max_length=300, null=True, upload_to=profiles.models.user_directory_path, verbose_name='фото')),
                ('number_of_run', models.IntegerField(null=True, verbose_name='номер пробежки')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
        ),
        migrations.CreateModel(
            name='RunnerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_select', models.IntegerField(choices=[(6, '06.09'), (7, '07.09'), (8, '08.09'), (9, '09.09'), (10, '10.09'), (11, '11.09'), (12, '12.09'), (13, '13.09'), (14, '14.09'), (15, '15.09'), (16, '16.09'), (17, '17.09'), (18, '18.09'), (19, '19.09'), (20, '20.09'), (21, '21.09'), (22, '22.09'), (23, '23.09'), (24, '24.09'), (25, '25.09'), (26, '26.09'), (27, '27.09'), (28, '28.09'), (29, '29.09'), (30, '30.09'), (1, '01.10'), (2, '02.10'), (3, '03.10'), (4, '04.10'), (5, '05.10')], db_index=True, default=1, verbose_name='день пробега')),
                ('day_distance', models.FloatField(db_index=True, help_text='введите в формате 10,23', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='дистанция за день')),
                ('day_time', models.TimeField(help_text='введите в формате 00:00:00', verbose_name='введите время пробега')),
                ('day_average_temp', models.TimeField(help_text='введите в формате 00:00:00', verbose_name='средний темп')),
                ('ball', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='баллы за пробежку')),
                ('number_of_run', models.IntegerField(choices=[(1, 1), (2, 2)], db_index=True, default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='номер пробежки')),
                ('run_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на пробег')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время внесения пробежки')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения пробежки')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner', to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
            options={
                'verbose_name': 'ежедневный забег',
                'verbose_name_plural': 'пробеги по дням',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField(blank=True, db_index=True, verbose_name='итоговый пробег')),
                ('total_time', models.TimeField(blank=True, db_index=True, verbose_name='общее время пробега')),
                ('total_average_temp', models.TimeField(blank=True, verbose_name='средний темп за все время')),
                ('total_days', models.IntegerField(db_index=True, null=True, verbose_name='дни пробега')),
                ('total_runs', models.IntegerField(db_index=True, null=True, verbose_name='количество пробежек')),
                ('total_balls', models.IntegerField(db_index=True, null=True, verbose_name='общая сумма баллов')),
                ('is_qualificated', models.BooleanField(default=False, verbose_name='прошел квалификацию')),
                ('runner_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
            options={
                'verbose_name': 'итоговая статистика',
                'verbose_name_plural': 'итоговая статистика',
            },
        ),
    ]
