# Generated by Django 5.0.6 on 2024-06-15 08:08

import django.core.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestFiveRunners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(db_index=True, null=True, unique=True, verbose_name='команда')),
                ('age18', models.IntegerField(db_index=True, null=True, verbose_name='возраст до 18')),
                ('age35', models.IntegerField(db_index=True, null=True, verbose_name='возраст 18-35')),
                ('age49', models.IntegerField(db_index=True, verbose_name='возраст 36-49')),
                ('ageover50', models.IntegerField(db_index=True, null=True, verbose_name='возраст 50+')),
                ('balls', models.IntegerField(db_index=True, null=True, verbose_name='баллы')),
            ],
        ),
        migrations.CreateModel(
            name='UserImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_select', models.IntegerField(null=True, verbose_name='день пробежки')),
                ('photo', models.FileField(blank=True, max_length=300, null=True, upload_to=profiles.models.user_directory_path, verbose_name='фото')),
                ('number_of_run', models.IntegerField(null=True, verbose_name='номер пробежки')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
        ),
        migrations.CreateModel(
            name='RunnerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_select', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=15, verbose_name='день пробега')),
                ('day_distance', models.FloatField(help_text='введите в формате 10,23', validators=[django.core.validators.MinValueValidator(1)], verbose_name='дистанция за день')),
                ('day_time', models.TimeField(help_text='введите в формате 00:00:00', verbose_name='введите время пробега')),
                ('day_average_temp', models.TimeField(help_text='введите в формате 00:00:00', verbose_name='средний темп')),
                ('ball', models.IntegerField(blank=True, null=True, verbose_name='баллы за пробежку')),
                ('number_of_run', models.IntegerField(choices=[(1, 1), (2, 2)], default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='номер пробежки')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner', to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
            options={
                'verbose_name': 'ежедневный забег',
                'verbose_name_plural': 'пробеги по дням',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField(blank=True, verbose_name='итоговый пробег')),
                ('total_time', models.TimeField(blank=True, verbose_name='общее время пробега')),
                ('total_average_temp', models.TimeField(blank=True, verbose_name='средний темп за все время')),
                ('total_days', models.IntegerField(null=True, verbose_name='дни пробега')),
                ('total_runs', models.IntegerField(null=True, verbose_name='количество пробежек')),
                ('total_balls', models.IntegerField(null=True, verbose_name='общая сумма баллов')),
                ('is_qualificated', models.BooleanField(default=False, verbose_name='прошел квалификацию')),
                ('runner_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
            options={
                'verbose_name': 'итоговая статистика',
                'verbose_name_plural': 'итоговая статистика',
            },
        ),
    ]
