# Generated by Django 5.0.6 on 2024-05-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='runner_stat',
            field=models.CharField(unique=True, verbose_name='участник'),
        ),
    ]
