# Generated by Django 5.0.6 on 2024-05-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_statistic_runner_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='runner_stat',
            field=models.CharField(verbose_name='участник'),
        ),
    ]
