# Generated by Django 5.0.6 on 2024-09-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_runnerday_day_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='day_select',
            field=models.TextField(null=True, verbose_name='день пробежки'),
        ),
    ]
