# Generated by Django 5.0.6 on 2024-06-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_runnerday_day_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerday',
            name='day_distance',
            field=models.FloatField(help_text='введите в формате 10,23', verbose_name='дистанция за день'),
        ),
    ]
