# Generated by Django 5.0.6 on 2024-09-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_photo_day_select_alter_runnerday_day_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerday',
            name='day_select',
            field=models.IntegerField(db_index=True, default=1, verbose_name='день пробега'),
        ),
    ]
