# Generated by Django 5.0.6 on 2024-05-29 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_runnerday_day_select_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='total_days',
            field=models.IntegerField(default=0, verbose_name='дни пробега'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_runs',
            field=models.IntegerField(default=0, verbose_name='количество пробежек'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runnerday',
            name='day_select',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=29, verbose_name='день пробега'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='runner_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='участник'),
        ),
    ]
