# Generated by Django 5.0.6 on 2024-09-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_statistic_total_balls_for_champ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerday',
            name='day_select',
            field=models.IntegerField(choices=[(26, 26), (25, 25)], db_index=True, default=26, verbose_name='день пробега'),
        ),
    ]
