# Generated by Django 5.0.6 on 2024-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_runnerday_day_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerday',
            name='day_select',
            field=models.IntegerField(choices=[(3, 3), (2, 2)], db_index=True, default=3, verbose_name='день пробега'),
        ),
    ]
