# Generated by Django 5.0.6 on 2024-06-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_runnerday_day_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestFiveRunners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(db_index=True, null=True, unique=True, verbose_name='команда')),
                ('age18', models.IntegerField(db_index=True, null=True, verbose_name='возраст до 18')),
                ('age35', models.IntegerField(db_index=True, null=True, verbose_name='возраст 18-35')),
                ('age49', models.IntegerField(db_index=True, verbose_name='возраст 36-49')),
                ('ageover50', models.IntegerField(db_index=True, null=True, verbose_name='возраст 50+')),
                ('balls', models.IntegerField(db_index=True, null=True, verbose_name='баллы')),
            ],
        ),
    ]
