# Generated by Django 5.0.6 on 2024-10-03 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_runnerday_day_select'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='участник'),
        ),
        migrations.AlterField(
            model_name='runnerday',
            name='day_select',
            field=models.IntegerField(choices=[(3, 3), (2, 2)], db_index=True, default=3, verbose_name='день пробега'),
        ),
    ]
