# Generated by Django 5.0.6 on 2024-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_runnerday_calory_remove_runnerday_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='ball',
            field=models.IntegerField(blank=True, null=True, verbose_name='баллы'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='day_select',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=4, verbose_name='день пробега'),
        ),
        migrations.AlterField(
            model_name='runnerday',
            name='day_select',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=4, verbose_name='день пробега'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_days',
            field=models.IntegerField(null=True, verbose_name='дни пробега'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_runs',
            field=models.IntegerField(null=True, verbose_name='количество пробежек'),
        ),
    ]
