# Generated by Django 5.0.6 on 2024-07-03 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_groupsresult_group_and_more'),
        ('profiles', '0008_alter_championat_team_alter_runnerday_day_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championat',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teams', verbose_name='команда'),
        ),
    ]
