# Generated by Django 5.0.6 on 2024-10-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_runnerday_day_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='runner_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.runnerday', verbose_name='день пробежки'),
        ),
    ]
