# Generated by Django 5.0.6 on 2024-10-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_photo_runner_alter_runnerday_day_select'),
        ('profiles', '0010_photo_runner_day'),
    ]

    operations = [
    ]
