# Generated by Django 5.0.6 on 2024-06-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_statistic_ball_runnerday_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='total_balls',
            field=models.IntegerField(null=True, verbose_name='общая сумма баллов'),
        ),
    ]
