# Generated by Django 5.0.6 on 2024-06-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_bestfiverunners_age_bestfiverunners_age18_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestfiverunners',
            name='team',
            field=models.IntegerField(db_index=True, null=True, unique=True, verbose_name='команда'),
        ),
    ]
