# Generated by Django 5.0.6 on 2024-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_merge_20241004_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='day_select',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='number_of_run',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='runner',
        ),
        migrations.AlterField(
            model_name='runnerday',
            name='day_select',
            field=models.IntegerField(choices=[(4, 4), (3, 3)], db_index=True, default=4, verbose_name='день пробега'),
        ),
    ]
