# Generated by Django 5.0.6 on 2024-06-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_statistic_total_balls'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='number_of_run',
            field=models.IntegerField(default=1, verbose_name='номер пробежки'),
        ),
    ]
