# Generated by Django 5.0.6 on 2024-10-04 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_photo_day_select_remove_photo_number_of_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='runner_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.runnerday', verbose_name='день пробежки'),
        ),
    ]
