# Generated by Django 5.0.6 on 2024-08-17 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_runnerday_day_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='runnerday',
            name='day_select',
            field=models.DateField(db_index=True, default=17, verbose_name='день пробега'),
        ),
    ]
