# Generated by Django 5.0.6 on 2024-06-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_bestfiverunners'),
        ('profiles', '0013_alter_bestfiverunners_team'),
    ]

    operations = [
    ]
