# Generated by Django 5.0.6 on 2024-08-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_runnerday_day_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerday',
            name='day_select',
            field=models.IntegerField(choices=[(609, '6.09'), (709, '7.09'), (809, '8.09'), (909, '9.09'), (1009, '10.09'), (11.09, '11.09'), (1209, '12.09'), (1309, '13.09'), (1409, '14.09'), (15.09, '15.09'), (16.09, '16.09'), (1709, '17.09'), (1809, '18.09'), (1909, '19.09'), (2009, '20.09'), (21.09, '21.09'), (2209, '22.09'), (2309, '23.09'), (2409, '24.09'), (2509, '25.09'), (26.09, '26.09'), (2709, '27.09'), (2809, '28.09'), (2909, '29.09'), (3009, '30.09'), (1.1, '1.10'), (210, '2.10'), (310, '3.10'), (410, '4.10'), (510, '5.10'), (6.1, '6.10'), (710, '7.10')], db_index=True, default=17, verbose_name='день пробега'),
        ),
    ]
