# Generated by Django 5.0.6 on 2024-10-06 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_runnerday_day_select'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='runnerday',
            name='day_select',
            field=models.IntegerField(choices=[(30, '30 сентября'), (1, '01 октября'), (2, '02 октября'), (3, '03 октября'), (4, '04 октября'), (5, '05 октября'), (6, '06 октября'), (7, '07 октября')], db_index=True, default=6, verbose_name='день пробега'),
        ),
    ]
