# Generated by Django 5.0.6 on 2024-06-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_runnerday_number_of_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='day_select',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='number_of_run',
        ),
    ]
