# Generated by Django 5.0.6 on 2024-06-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_remove_photo_day_select_remove_photo_number_of_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='day_select',
            field=models.IntegerField(default=1, verbose_name='день пробежки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='number_of_run',
            field=models.IntegerField(default=0, verbose_name='номер пробежки'),
            preserve_default=False,
        ),
    ]
