# Generated by Django 5.0.6 on 2024-10-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_runnerday_day_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerday',
            name='day_select',
            field=models.IntegerField(choices=[(30, '30 сентября'), (1, '01 октября'), (2, '02 октября'), (3, '03 октября'), (4, '04 октября'), (5, '05 октября'), (6, '06 октября'), (7, '07 октября'), (8, '08 октября'), (9, '09 октября'), (10, '10 октября'), (11, '11 октября'), (12, '12 октября'), (13, '13 октября'), (14, '14 октября'), (15, '15 октября'), (16, '16 октября'), (17, '17 октября'), (18, '18 октября'), (19, '19 октября'), (20, '20 октября'), (21, '21 октября')], db_index=True, default=10, verbose_name='день пробега'),
        ),
    ]
