# Generated by Django 5.0.6 on 2024-06-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='runner_family',
        ),
        migrations.AlterField(
            model_name='family',
            name='family_title',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
    ]
