# Generated by Django 5.0.6 on 2024-06-06 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='runner_age',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(5)], verbose_name='возраст'),
        ),
    ]
