# Generated by Django 5.0.6 on 2024-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='keyword',
            field=models.CharField(default='qwe', max_length=20, verbose_name='кодовое слово'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='not_running',
            field=models.BooleanField(default=False, verbose_name='не бегает'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='ответственный'),
        ),
        migrations.DeleteModel(
            name='KeyWordClass',
        ),
    ]
