# Generated by Django 5.0.6 on 2024-06-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_runner_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_title',
            field=models.CharField(default=0, max_length=100, verbose_name='Название команды'),
            preserve_default=False,
        ),
    ]
