# Generated by Django 5.0.6 on 2024-06-03 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teams_keyword_user_not_running_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='runner_family',
            field=models.ManyToManyField(blank=True, related_name='runners_family', to=settings.AUTH_USER_MODEL, verbose_name='Семья'),
        ),
    ]
