# Generated by Django 5.0.6 on 2024-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_family_runner_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='runner_family',
            field=models.ManyToManyField(blank=True, related_name='runners_family', to='core.family', verbose_name='группа'),
        ),
    ]
