# Generated by Django 5.0.6 on 2024-06-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_family_family_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='runner_status',
            field=models.CharField(choices=[(1, 'Участник'), (2, 'Семейный')], default=1, verbose_name='Ваш статус'),
        ),
    ]
