# Generated by Django 5.0.6 on 2024-06-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_family_runner_family'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='family_title',
            new_name='group_title',
        ),
    ]
