# Generated by Django 5.0.6 on 2024-06-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_family_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='runner_family',
            new_name='runners',
        ),
    ]
