# Generated by Django 5.0.6 on 2024-06-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_runner_family_group_runners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='runners',
        ),
    ]
