# Generated by Django 5.0.6 on 2024-06-17 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_group_runners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группа участника', 'verbose_name_plural': 'группа участника'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='runner',
        ),
        migrations.AddField(
            model_name='user',
            name='runner_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.group', verbose_name='группа участника'),
        ),
    ]
