# Generated by Django 5.0.6 on 2024-06-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_group_options_remove_group_runner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='runner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='runners_groups', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
            preserve_default=False,
        ),
    ]
