# Generated by Django 5.0.6 on 2024-06-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_group_runner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='runner',
        ),
    ]
