# Generated by Django 5.0.6 on 2024-06-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_group_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='choice',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
