# Generated by Django 5.0.6 on 2024-06-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_group_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='choice',
        ),
        migrations.AlterField(
            model_name='user',
            name='runner_category',
            field=models.PositiveIntegerField(choices=[(1, 'Новичок'), (2, 'Любитель'), (3, 'Профи')], db_index=True, default=1, verbose_name='Категория'),
        ),
    ]
