# Generated by Django 5.0.6 on 2024-06-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_group_choice_alter_user_runner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_group',
            field=models.BooleanField(default=False, null=True, verbose_name='Старший группы'),
        ),
    ]
