# Generated by Django 5.0.6 on 2024-06-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_can_create_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название группы'),
        ),
    ]
