# Generated by Django 5.0.6 on 2024-06-24 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_group_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='runner_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teams', verbose_name='команда'),
        ),
    ]
