# Generated by Django 5.0.6 on 2024-06-28 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_runner_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comands_total_members', models.PositiveIntegerField(default=0, verbose_name='общее число участников')),
                ('comand_total_distance', models.PositiveIntegerField(default=0, verbose_name='общее расстояние')),
                ('comand_total_time', models.TimeField(default=0, verbose_name='общее время')),
                ('comand_total_balls', models.PositiveIntegerField(default=0, verbose_name='общее количество баллов')),
                ('comand_average_temp', models.TimeField(default=0, verbose_name='среднее время команды')),
                ('comand_total_runs', models.PositiveIntegerField(default=0, verbose_name='общее количество пробежек')),
                ('comand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teams', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'Общие результаты команд',
                'verbose_name_plural': ' Общие результаты команд',
            },
        ),
        migrations.CreateModel(
            name='GroupsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_total_members', models.PositiveIntegerField(default=0, verbose_name='общее число участников')),
                ('group_total_time', models.TimeField(default=0, verbose_name='общее время')),
                ('group_total_balls', models.PositiveIntegerField(default=0, verbose_name='общее количество баллов')),
                ('group_total_distance', models.PositiveIntegerField(default=0, verbose_name='общее расстояние')),
                ('group_average_temp', models.TimeField(default=0, verbose_name='среднее время команды')),
                ('group_total_runs', models.PositiveIntegerField(default=0, verbose_name='общее количество пробежек')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'Общие результаты групп',
                'verbose_name_plural': ' Общие результаты групп',
            },
        ),
    ]
