# Generated by Django 5.0.6 on 2024-06-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comandsresult_groupsresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsresult',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='groupsresult',
            name='group_average_temp',
            field=models.TimeField(default=0, verbose_name='среднее время группы'),
        ),
    ]
