# Generated by Django 5.0.6 on 2024-07-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_groupsresult_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='runner_status',
        ),
    ]
