# Generated by Django 5.0.6 on 2024-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_user_runner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='runner_gender',
            field=models.CharField(choices=[('м', 'Мужской'), ('ж', 'Женский')], default='м', max_length=1, verbose_name='пол участника'),
        ),
    ]
